title:   Kyu Tech Blog

collections:
  projects:
    output: true
    
markdown: kramdown
github: https://github.com/J-Kyu
 
logo:             images/logo.png # logo visible in the topbar
thumbnail:             images/bg.jpg # logo visible in the topbar
url: https://j-kyu.github.io
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"


plugins: [jekyll-youtube]