title:   Kyu Tech Blog

collections:
  projects:
    output: true

logo:             images/logo.png # logo visible in the topbar
thumbnail:             images/bg.jpg # logo visible in the topbar
url: http://localhost:4000
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"