title:   Kyu Tech Blog

collections:
  projects:
    output: true
    
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'
github: https://github.com/J-Kyu
 
logo: /images/logo.png # logo visible in the topbar
thumbnail: /images/bg.jpg # logo visible in the topbar
url: https://j-kyu.github.io
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"