title:   Kyu Tech Blog

collections:
  authors:
    output: true

logo:             images/logo.png # logo visible in the topbar
url: http://localhost:4000
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"